### ISSUE TITLE
Add favicon to the home page 

### ISSUE THREAD

**Issue by ankman007** [ankman007/Travel-Website#1]
### Description 
You will need to find something related to travel/explore/world that relates to overall theme of this travel website from site like favicon.io and add it as favicon. 

### Screenshot
![Screenshot (5)](https://github.com/ankman007/Travel-Website/assets/108212023/a7290f68-5cfe-4cce-a797-6e7829b1b6a4)

**Comment by vd89** [comment]
Hey @ankman007, 
Will be ready to fix the same for you 
assign to me and will fix that

**Comment by ankman007** [comment]
> Hey @ankman007, Will be ready to fix the same for you assign to me and will fix that

Sure, I've assigned the issue to you.

**Comment by vd89** [comment]
Thanks 
will be fixing that

**Comment by vd89** [comment]
- have fixed the issuer and raised the pr for the same 
- can you mark it under #hactoberfest and #hactoberfest-accepted label 
-

**Comment by ankman007** [comment]
> * have fixed the issuer and raised the pr for the same
> * can you mark it under #hactoberfest and #hactoberfest-accepted label

Have added the label, thanks.
