### ISSUE TITLE
 contributing.md missing

### ISSUE THREAD

**Issue by shivang21007** [ankman007/Travel-Website#11]
Repo must have contributing.md file under Hacktoberfest.
please assign this issue to me ,
and label it under hacktoberfest and  hacktoberfest-accepted -
![image](https://github.com/ankman007/Travel-Website/assets/98748694/4e0e09a6-9943-4b40-82f1-544080fd001b)

**Comment by ankman007** [comment]
@shivang21007 Thanks for the recommendation but I don't think it is required for the project atm. You can add contribution guidelines in README.md file itself. Also, if you want to work with the issue under hacktoberfest and hacktoberfest-accepted, there are other issues within this repository itself. You can work on those.
