### ISSUE TITLE
[BUG]: Make some stylistic changes to the overall webpage. 

### ISSUE THREAD

**Issue by ankman007** [ankman007/Travel-Website#12]
### Description
The changes you need to make are below:

- The "Get a Free Quote" and number are at the center of the header, it should be on the far right of the screen.

![to the right](https://github.com/ankman007/Travel-Website/assets/108212023/4021fc8c-855e-471b-ad90-d2626bb88580)
_Screenshot 1_

- When you hover over the nav items, it affects the whole content. You need to fix it in a way that it only affect the container of nav items.

![navigation hover](https://github.com/ankman007/Travel-Website/assets/108212023/dc0b00d1-abcd-4edc-998a-84da4633cc09)
_Screenshot 2_

### Guidelines
When submitting a PR, include videos and photos of the changes you have made in the repo with proper description. 
Also, please don't wait for maintainers to assign you the issue. You can directly make a PR.

**Comment by devharsh007** [comment]
<img width="1427" alt="image" src="https://github.com/ankman007/Travel-Website/assets/69196581/87f22326-6834-4947-b93b-c98d55b12d09">
- Free Quote is moved to right
- Hover problem fixed

**Comment by ankman007** [comment]
> If u need any help regarding this . .. dm me on social media.

Well there is another issue with in this repo regarding responsive design. If you can fix that that would be great.

**Comment by devharsh007** [comment]
Yeah Sure ! but it will take some time. ;)
