### ISSUE TITLE
[BUG]: Add CSS styling to make the footer more appealing.

### ISSUE THREAD

**Issue by ankman007** [ankman007/Travel-Website#14]
### Description 
You need to add css to make the footer more appealing. There is strict guidelines for this issue, you can get creative with this issue. 
![fix footer styling](https://github.com/ankman007/Travel-Website/assets/108212023/f751c565-94f9-4c16-83d7-4bba7d2db32f)

Note: When submitting a PR, include videos and photos of the changes you have made in the repo with proper description.
Also, please don't wait for maintainers to assign you the issue. You can directly make a PR.

**Comment by devharsh007** [comment]
You want to change the footer only? the last line?  or the white portion too?

**Comment by ankman007** [comment]
> You want to change the footer only? the last line? or the white portion too?

Change last two section. That would be great.

**Comment by devharsh007** [comment]
Okay !
