### ISSUE TITLE
Add some kind of hover effect over the Navigation items

### ISSUE THREAD

**Issue by ankman007** [ankman007/Travel-Website#4]
### Description
Use CSS to create a cool hover effect over the Nav items. Plus points if you add the effects to all other buttons & icons in the home page. 

### Screenshots
![ww](https://github.com/ankman007/Travel-Website/assets/108212023/c42a5998-47ac-41b0-bd11-c92d8a7b1ebd)

**Comment by Johneriksson88** [comment]
Hello!
I'm pretty new to this but I'm confident I can fix this issue. What do I do to get assigned to this?

**Comment by harsh-p05** [comment]
hay, @ankman007 
I am new to this project but i know css and html can I get the chance to do this

**Comment by ankman007** [comment]
> Hello! I'm pretty new to this but I'm confident I can fix this issue. What do I do to get assigned to this?

No need just make a pull request.

**Comment by ankman007** [comment]
> hay, @ankman007 I am new to this project but i know css and html can I get the chance to do this

Sorry man, I've already assigned this issue to the other guy. But you can look into other issues within this repo. 
If you up to it, you can add media queries to make this website responsive.

**Comment by Johneriksson88** [comment]
Thanks man, I'll get on it tonight.

**Comment by harsh-p05** [comment]
- hey @ankman007  

- I have raised the pr for the same and resolved the issue
